# Generated by Django 4.1.3 on 2022-12-08 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('assemblyID', models.AutoField(primary_key=True, serialize=False)),
                ('assemblyName', models.CharField(max_length=100)),
                ('assemblyQuantity', models.IntegerField()),
                ('assemblySlug', models.SlugField(default='assembly-', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('carName', models.CharField(max_length=10)),
                ('carYear', models.IntegerField()),
                ('carSlug', models.SlugField(default='car-', unique=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FastenerSubtype',
            fields=[
                ('fastenerSubtypeID', models.AutoField(primary_key=True, serialize=False)),
                ('fastenerSubtypeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('partID', models.AutoField(primary_key=True, serialize=False)),
                ('partName', models.CharField(max_length=100)),
                ('makeBuy', models.BooleanField()),
                ('partCost', models.FloatField(null=True)),
                ('partQuantity', models.IntegerField(default=1)),
                ('partComment', models.CharField(max_length=100, null=True)),
                ('partSlug', models.SlugField(default='part-', unique=True)),
                ('assemblyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.assembly')),
            ],
        ),
        migrations.CreateModel(
            name='PmftCategory',
            fields=[
                ('pmftID', models.AutoField(primary_key=True, serialize=False)),
                ('pmftCatagory', models.CharField(max_length=100)),
                ('pmftType', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subteam',
            fields=[
                ('teamName', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('abbr', models.CharField(max_length=10, unique=True)),
                ('subteamSlug', models.SlugField(default='team-', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rank', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLinking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teamHead', models.BooleanField(default=False)),
                ('subteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.subteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('systemID', models.AutoField(primary_key=True, serialize=False)),
                ('systemName', models.CharField(max_length=30)),
                ('costed', models.BooleanField(default=False)),
                ('systemSlug', models.SlugField(default='system-', unique=True)),
                ('carID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.car')),
            ],
        ),
        migrations.AddField(
            model_name='subteam',
            name='systems',
            field=models.ManyToManyField(blank=True, to='tool.system'),
        ),
        migrations.CreateModel(
            name='PMFT',
            fields=[
                ('pmftID', models.AutoField(primary_key=True, serialize=False)),
                ('pmftName', models.CharField(max_length=100)),
                ('pmftComment', models.CharField(max_length=100, null=True)),
                ('pmftCost', models.FloatField(default=0)),
                ('pmftCostComment', models.CharField(max_length=100, null=True)),
                ('pmftQuantity', models.FloatField(default=1)),
                ('pmftType', models.CharField(max_length=5)),
                ('pmftSlug', models.SlugField(default='pmft-', unique=True)),
                ('partID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.part')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSubtype',
            fields=[
                ('materialSubtypeID', models.AutoField(primary_key=True, serialize=False)),
                ('materialSubtypeName', models.CharField(max_length=100)),
                ('materialCategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.pmftcategory')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTool',
            fields=[
                ('individualToolID', models.AutoField(primary_key=True, serialize=False)),
                ('individualToolName', models.CharField(max_length=100)),
                ('toolCost', models.FloatField(null=True)),
                ('toolComment', models.CharField(max_length=100, null=True)),
                ('toolCategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.pmftcategory')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualProcess',
            fields=[
                ('individualProcessID', models.AutoField(primary_key=True, serialize=False)),
                ('individualProcessName', models.CharField(max_length=100)),
                ('processCost', models.FloatField(null=True)),
                ('processComment', models.CharField(max_length=100, null=True)),
                ('processCategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.pmftcategory')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualMaterial',
            fields=[
                ('individualMaterialID', models.AutoField(primary_key=True, serialize=False)),
                ('individualMaterialName', models.CharField(max_length=100)),
                ('materialCost', models.FloatField(null=True)),
                ('materialCostComment', models.CharField(max_length=100, null=True)),
                ('imecheName', models.CharField(max_length=100, null=True)),
                ('materialComment', models.CharField(max_length=100)),
                ('individualMaterialSubtypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.materialsubtype')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualFastener',
            fields=[
                ('individualFastenerID', models.AutoField(primary_key=True, serialize=False)),
                ('individualFastenerName', models.CharField(max_length=100)),
                ('fastenerCost', models.FloatField(null=True)),
                ('fastenerComment', models.CharField(max_length=100, null=True)),
                ('individualFastenerSubtypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.fastenersubtype')),
            ],
        ),
        migrations.AddField(
            model_name='fastenersubtype',
            name='fastenerCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.pmftcategory'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('carYear', 'carName'), name='unique_carName_carYear'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='systemID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.system'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.useraccount'),
        ),
        migrations.AddConstraint(
            model_name='system',
            constraint=models.UniqueConstraint(fields=('systemName', 'carID'), name='unique_carID_systemName'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('partName', 'assemblyID'), name='unique_partName_assemblyID'),
        ),
        migrations.AddConstraint(
            model_name='assembly',
            constraint=models.UniqueConstraint(fields=('assemblyName', 'systemID'), name='unique_assemblyName_systemID'),
        ),
    ]
